[package]
name = "looper_core"
version = "0.1.0"
authors = ["Simon Persson <simon.persson@mykolab.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
log = "*"
mio = "*"
stash = { git = "https://github.com/Stebalien/stash-rs" }
